/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Content: typeof import('./src/components/layouts/content/content.vue')['default']
    ContentSpinner: typeof import('./src/components/layouts/content/content-spinner.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabNav: typeof import('element-plus/es')['ElTabNav']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    IconButton: typeof import('./src/components/icons/icon-button.vue')['default']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpBell: typeof import('~icons/ep/bell')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpDArrowLeft: typeof import('~icons/ep/d-arrow-left')['default']
    IEpDArrowRight: typeof import('~icons/ep/d-arrow-right')['default']
    IEpFullScreen: typeof import('~icons/ep/full-screen')['default']
    IEpMoon: typeof import('~icons/ep/moon')['default']
    IEpQuestionFilled: typeof import('~icons/ep/question-filled')['default']
    IEpSunny: typeof import('~icons/ep/sunny')['default']
    Loading: typeof import('./src/components/spinner/loading.vue')['default']
    Modal: typeof import('./src/components/modal/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollArea: typeof import('./src/components/scrollbar/scrollArea.vue')['default']
    ScrollAreaCorner: typeof import('radix-vue')['ScrollAreaCorner']
    ScrollAreaRoot: typeof import('radix-vue')['ScrollAreaRoot']
    ScrollAreaScrollbar: typeof import('radix-vue')['ScrollAreaScrollbar']
    ScrollAreaThumb: typeof import('radix-vue')['ScrollAreaThumb']
    ScrollAreaViewport: typeof import('radix-vue')['ScrollAreaViewport']
    Scrollbar: typeof import('./src/components/scrollbar/scrollbar.vue')['default']
    SidebarButton: typeof import('./src/components/widget/sidebar-btn/sidebar-button.vue')['default']
    SidebarCollapseButton: typeof import('./src/components/widget/sidebar-btn/sidebar-collapse-button.vue')['default']
    Spinner: typeof import('./src/components/spinner/spinner.vue')['default']
    Spinning: typeof import('./src/components/spinner/spinning.vue')['default']
    SvgIcon: typeof import('./src/components/icons/SvgIcon.vue')['default']
    Tabs: typeof import('./src/components/tabs/Tabs.vue')['default']
    ThemeButton: typeof import('./src/components/widget/theme-toggle/theme-button.vue')['default']
    ThemeToggle: typeof import('./src/components/widget/theme-toggle/theme-toggle.vue')['default']
  }
}
