packages:
  - internal/*
  - internal/lint-configs/*
  - packages/*
  - packages/effects/*
  - packages/effects/common-ui/components/*
  - apps/*
  - apps/frontend/*
  - playground/*
  - scripts/*

catalog:
  execa: ^9.6.0
  cac: ^6.7.14
  '@element-plus/icons-vue': ^2.3.1
  '@vueuse/core': ^13.6.0
  axios: ^1.11.0
  clsx: ^2.1.1
  element-plus: ^2.10.4
  jsonwebtoken: ^9.0.2
  lodash.clonedeep: ^4.5.0
  lodash.get: ^4.4.2
  lodash.set: ^4.3.2
  mockjs: ^1.1.0
  nprogress: ^0.2.0
  pinia: ^3.0.3
  pinia-plugin-persistedstate: ^4.4.1
  qs: ^6.14.0
  radix-vue: ^1.9.17
  secure-ls: ^2.0.0
  vue: ^3.5.17
  vue-router: ^4.5.1
  dotenv: 17.2.0
  tsup: 8.5.0
  unbuild: ^3.6.0
  '@manypkg/get-packages': ^3.0.0
  find-up: 7.0.0
  '@changesets/cli': ^2.29.5
  '@iconify-json/ep': ^1.2.2
  '@tsconfig/node22': ^22.0.2
  '@types/jsonwebtoken': ^9.0.10
  '@types/lodash.clonedeep': ^4.5.9
  '@types/lodash.get': ^4.4.9
  '@types/lodash.set': ^4.3.9
  '@types/mockjs': ^1.0.10
  '@types/node': ^22.17.0
  '@types/nprogress': ^0.2.3
  '@types/qs': ^6.14.0
  '@vitejs/plugin-vue': ^5.2.4
  '@vue/eslint-config-prettier': ^10.2.0
  '@vue/eslint-config-typescript': ^14.6.0
  '@vue/tsconfig': ^0.7.0
  eslint: ^9.32.0
  eslint-plugin-vue: ~10.0.1
  npm-run-all2: ^7.0.2
  prettier: 3.5.3
  sass: 1.89.2
  sass-loader: ^16.0.5
  typescript: 5.8.3
  unplugin-auto-import: ^19.3.0
  unplugin-icons: ^22.2.0
  unplugin-vue-components: ^28.8.0
  vite: ^6.3.5
  vite-plugin-html: ^3.2.2
  vite-plugin-mock: ^3.0.2
  vite-plugin-svg-icons: ^2.0.1
  vite-plugin-vue-devtools: 7.7.7
  vue-tsc: ^2.2.12
