/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    GraphicalContainer: typeof import('./components/biobank/graphicalContainer/graphicalContainer.vue')['default']
    IconButton: typeof import('./components/icons/icon-button.vue')['default']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpBell: typeof import('~icons/ep/bell')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpDArrowLeft: typeof import('~icons/ep/d-arrow-left')['default']
    IEpDArrowRight: typeof import('~icons/ep/d-arrow-right')['default']
    IEpFullScreen: typeof import('~icons/ep/full-screen')['default']
    IEpMoon: typeof import('~icons/ep/moon')['default']
    IEpQuestionFilled: typeof import('~icons/ep/question-filled')['default']
    IEpSunny: typeof import('~icons/ep/sunny')['default']
    Loading: typeof import('./components/spinner/loading.vue')['default']
    Modal: typeof import('./components/modal/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollArea: typeof import('./components/scrollbar/scrollArea.vue')['default']
    ScrollAreaCorner: typeof import('radix-vue')['ScrollAreaCorner']
    ScrollAreaRoot: typeof import('radix-vue')['ScrollAreaRoot']
    ScrollAreaScrollbar: typeof import('radix-vue')['ScrollAreaScrollbar']
    ScrollAreaThumb: typeof import('radix-vue')['ScrollAreaThumb']
    ScrollAreaViewport: typeof import('radix-vue')['ScrollAreaViewport']
    Scrollbar: typeof import('./components/scrollbar/scrollbar.vue')['default']
    SidebarButton: typeof import('./components/widget/sidebar-btn/sidebar-button.vue')['default']
    SidebarCollapseButton: typeof import('./components/widget/sidebar-btn/sidebar-collapse-button.vue')['default']
    Spinner: typeof import('./components/spinner/spinner.vue')['default']
    SubconLiquidNitrogenTank: typeof import('./components/biobank/subContainer/liquidNitrogenTank/subconLiquidNitrogenTank.vue')['default']
    SubconRefrigerator: typeof import('./components/biobank/subContainer/refrigerator/subconRefrigerator.vue')['default']
    Tabs: typeof import('./components/tabs/Tabs.vue')['default']
    ThemeButton: typeof import('./components/widget/theme-toggle/theme-button.vue')['default']
    ThemeToggle: typeof import('./components/widget/theme-toggle/theme-toggle.vue')['default']
  }
}
