export const menuPageData = {
  icon: 'dh_whp',
  key: 'weihuapin:menu',
  label: 'hazardousChemicals',
  children: [
    {
      key1: 'whpJichuguanli',
      key: 'whp:jichuguanli',
      label: 'basicManagement',
      icon: 'jcxx_menu',
      children: [
        {
          key1: 'chemicalsBasicInformation',
          key: 'whp:jichuxinxi',
          label: 'basicInformation',
          path: '/jichuxinxi/whpJichuXinxi/whpJichuXinxi',
        },
        {
          key1: 'chemicalsList',
          key: 'whp:whpminglu',
          label: 'hazardousChemicalsList',
          icon: 'dh_whpml',
          path: '/jichuxinxi/whpminglu/whpmingluchaxun',
        },
        {
          key1: 'incompatibleChemicals',
          key: 'whp:buxiangrong',
          label: 'Incompatible',
          icon: 'dh_whpml',
          path: '/weihuapin/buxiangrong/buxiangrong',
        },
      ],
    },
    {
      key1: 'whpCaigouguanli',
      key: 'whp:caigouguanli',
      label: 'purchasingManagement',
      icon: 'dh_cggl',
      children: [
        {
          key1: 'chemicalsApply',
          key: 'whpshengou:whp_gzt',
          label: 'forPurchase',
          path: '/weihuapin/whpshengou/whpshengou',
        },
        {
          key1: 'chemicalsProcurement',
          key: 'whp:caigou',
          label: 'procurement',
          path: '/weihuapin/caigou/caigouchaxun',
        },
      ],
    },

    {
      key1: 'whpKucunguanli',
      key: 'whp:kucunguanli',
      label: 'inventoryManagement',
      icon: 'dh_kcgl',
      children: [
        {
          key1: 'chemicalsPutInStorage',
          key: 'whp:ruku',
          label: 'putInStorage',
          path: '/weihuapin/ruku/rukuchaxun',
        },
        {
          key1: 'chemicalsInventoryQuery',
          key: 'whp:kucun',
          label: 'inventoryQuery',
          path: '/weihuapin/kucunchaxun/kucunchaxun',
        },
        {
          key1: 'temporarystorageCabinetInventory',
          key: 'whp:zancunguikucun',
          label: 'cabinetInventory',
          path: '/weihuapin/zancunguikucun/zancunguikucun',
        },
        {
          key1: 'SmartCabinet',
          key: 'whp:zng',
          label: 'smartArk',
          icon: 'dh_znsjg',
          path: '/weihuapin/zhinenggui/zhinenggui',
        },
        {
          key1: 'intelligentLock',
          key: 'ZNYJ:zhinengsuo',
          label: 'zhinengsuo',
          icon: 'menu_zns',
          path: '/weihuapin/zhinengsuo/zhinengsuo',
        },
        {
          key1: 'chemicalsInventory',
          key: 'weihuapin:pandian',
          label: 'inventory',
          path: '/weihuapin/pandian/pandian',
        },
        {
          key1: 'chemicalsInventoryRunningWater',
          key: 'whp:kucunliushui',
          label: 'inventoryTheWater',
          path: '/weihuapin/kucunliushui/kucunliushuichaxun',
        },
        {
          key1: 'chemicalsHistoryQuery',
          key: 'whp:lishichaxun',
          label: 'historyQuery',
          path: '/weihuapin/lishichaxun/lishichaxun',
        },
      ],
    },
    {
      key1: 'whpLingyongguanli',
      key: 'whp:lingyongguanli',
      label: 'CollectionManagement',
      icon: 'dh_lygl',
      children: [
        {
          key1: 'chemicalsRecipients',
          key: 'whplingyong:whp_gzt',
          label: 'forRecipients',
          path: '/weihuapin/whplingyong/whplingyong',
        },
        {
          key1: 'myChemicals',
          key: 'whpguihuan:whp_gzt',
          label: 'myFor',
          path: '/weihuapin/whpguihuan/whpguihuan',
        },
        {
          key1: 'chemicalsAllocation',
          key: 'whp:diaobo',
          label: 'allocation',
          path: '/weihuapin/diaobo/diaobo',
        },
        {
          key1: 'chemicalsWarehouse',
          key: 'whp:chuku',
          label: 'recipientsWarehouse',
          path: '/weihuapin/lingyongchuku/chukuchaxun',
        },
        {
          key1: 'chemicalsReturn',
          key: 'weihuapin:whpguihuanchaxun',
          label: 'return',
          path: '/weihuapin/guihuan/whpguihuanchaxun',
        },
      ],
    },
    {
      key1: 'warehouseVr',
      key: 'whp:kfVr',
      label: 'warehouseVr',
      icon: 'syslx',
      path: '/weihuapin/kufangVr/kufangVr',
    },
    {
      key1: 'whpFeiqiwu',
      key: 'whp:feiqiwu',
      label: 'waste',
      icon: 'dh_fqw',
      children: [
        {
          key1: 'wasteCollection',
          key: 'whp:fqwsj',
          label: 'wasteCollection',
          path: '/weihuapin/feiqiwushouji/feiqiwuguanlichaxun',
        },
        {
          key1: 'transferProcessing',
          key: 'whp:fqwzycl',
          label: 'transferProcessing',
          path: '/weihuapin/zhuanyichuli/feiqiwuzhuanyichaxun',
        },
      ],
    },
    {
      key1: 'whpTongjifenxi',
      key: 'whp:tongjifenxi',
      label: 'statisticalAnalysis',
      icon: 'btn_tjfx',
      children: [
        {
          key1: 'chemicalsStatisticalProfile',
          key: 'whp:gaikuang',
          label: 'statisticalProfile',
          path: '/weihuapin/tongjifenxi/gaikuang/whptongjigaikuang',
        },
        {
          key1: 'chemicalsLibraryStatistics',
          key: 'whp:rukutj',
          label: 'libraryStatistics',
          path: '/weihuapin/tongjifenxi/rukutj/whprukutongji',
        },
        {
          key1: 'chemicalsInventoryStatistics',
          key: 'whp:kucuntj',
          label: 'inventoryStatistics',
          path: '/weihuapin/tongjifenxi/kucuntj/whpkucuntongji',
        },
        {
          key1: 'chemicalsOutboundStatistics',
          key: 'whp:chukutj',
          label: 'outboundStatistics',
          path: '/weihuapin/tongjifenxi/chukutj/whpchukutongji',
        },
        {
          key1: 'chemicalsUseStatistical',
          key: 'whp:shiyongtj',
          label: 'useStatistical',
          path: '/weihuapin/tongjifenxi/shiyongtj/whpshiyongtongji',
        },
        {
          key1: 'chemicalsProcurementStatistics',
          key: 'whp:caigoutj',
          label: 'procurementStatistics',
          path: '/weihuapin/tongjifenxi/caigoutj/whpcaigoutongji',
        },
        {
          key1: 'chemicalsAnnualStatistics',
          key: 'whp:niandutongji',
          label: 'AnnualStatistics',
          path: '/weihuapin/tongjifenxi/niandutongji/niandutongji',
        },
      ],
    },
  ],
}
